ticker_subset = ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'INTC', 'AMZN', 'GOOGL',
			  	 'FB', 'WDC', 'ATVI', 'LOGI', 'AXP', 'DAL', 'CMCSA', 'V',
			  	 'BRK.B', 'JNJ', 'AMJ', 'XOM', 'WMT', 'PG', 'BAC', 'MA',
			  	 'VZ', 'DIS', 'T', 'UNH', 'PFE', 'CSCO', 'CVX', 'HD', 'MRK',
			  	 'KO', 'WFC', 'PEP', 'BA', 'NFLX', 'C', 'MCD', 'WMT', 'ABT',
			  	 'ADBE', 'ORCL', 'PYPL', 'MDT', 'UNP', 'HON', 'CRM', 'PM',
			  	 'IBM', 'ACN', 'ABBV', 'TMO', 'COST', 'AMGN', 'UTX', 'LIN',
			  	 'AVGO', 'NKE', 'TXN', 'LLY', 'SBUX', 'NEE', 'MMM', 'AMT', 'MO',
			  	 'LMT', 'GE', 'DHR', 'GILD', 'QCOM', 'BKNG', 'USB', 'LOW', 'MDLZ',
			  	 'BMY', 'CME', 'ANTM', 'ADP', 'CAT', 'CVS', 'CB', 'UPS', 'CELG',
			  	 'CHTR', 'INTU', 'GS', 'COP', 'BDX', 'DUK', 'TJX', 'D', 'CL',
			  	 'PNC', 'CSX', 'SYK', 'CI', 'SO', 'DD', 'CCI', 'ISRG', 'BSX',
			  	 'MS', 'SPGI', 'NSC', 'NOC', 'BLK', 'SCHW', 'ZTS', 'RTN', 'SPG',
			  	 'MMC', 'ECL', 'PLD', 'PGR', 'SLB', 'EXC', 'ICE', 'APD', 'EOG',
			  	 'AIG', 'GM', 'ILMN', 'GD', 'DE', 'MET', 'KMB', 'AON', 'TGT', 'BIIB',
			  	 'ITW', 'VRTX', 'WM', 'AEP', 'COF', 'EQIX', 'PRU', 'AFL', 'WBA',
			  	 'AGN', 'KMI', 'TRV', 'FIS', 'EMR', 'AMAT', 'BK', 'F', 'FDX',
			  	 'DOW', 'BBT', 'MU', 'ROP', 'EL', 'SHW', 'EW', 'PSA', 'SRE', 'ADI',
			  	 'BAX', 'MAR', 'JCI', 'PSX', 'CTSH', 'OXY', 'APC', 'ROST', 'ADSK',
			  	 'FISV', 'HUM', 'DG', 'DAL', 'WMB', 'SYY', 'ETN', 'HCA', 'ALL', 'YUM',
			  	 'RHT', 'MPC', 'WELL', 'EBAY', 'STZ', 'MCO', 'VLO', 'GIS', 'PEG',
			  	 'TEL', 'XEL', 'ORLY', 'IR', 'HPQ', 'AVB', 'EA', 'ED', 'EQR', 'NEM',
			  	 'STI', 'VFC', 'LRCX', 'PAYX', 'PPG', 'APH', 'OKE', 'AZO', 'XLNX', 'HLT',
			  	 'ALXN', 'TWTR', 'WEC', 'MSI', 'AMD', 'DFS', 'MNST', 'SBAC', 'LUV',
			  	 'TROW', 'GPN', 'LYB', 'MCK', 'ZBH', 'ES', 'PCAR', 'GLW', 'DLR',
			  	 'DLTR', 'PXD', 'WLTW', 'TSN', 'DTE', 'VRSK', 'REGN', 'HRS', 'CERN',
			  	 'CMI', 'FTV', 'MTB', 'TDG', 'VTR', 'PPL', 'CNC', 'SYF', 'ADM', 'O',
			  	 'IQV', 'BLL', 'IDXX', 'FLT', 'ALGN', 'A', 'FE', 'INFO', 'VRSN',
			  	 'PH', 'STT', 'AWK', 'CTVA', 'EIX', 'FITB', 'TSS', 'BXP', 'SWK',
			  	 'RCL', 'CCL', 'LLL', 'AMP', 'CLX', 'MSCI', 'CXO', 'HIG', 'CTAS',
			  	 'MCHP', 'ESS', 'NTRS', 'HPE', 'AME', 'MKC', 'ROK', 'APTV', 'ETR',
			  	 'ULTA', 'CHD', 'MTD', 'HSY', 'KR', 'AEE', 'RSG', 'UAL', 'FAST',
			  	 'HAL', 'SNPS', 'CDNS', 'IP', 'KHC', 'KLAC', 'WY,' 'VMC', 'OMC',
			  	 'KEY', 'ARE', 'CBS', 'LH', 'CMG', 'RMD', 'FRC', 'CMS', 'CFG', 'AJG',
			  	 'NUE', 'MXIM', 'EFX', 'COO', 'ANSS', 'EVRG', 'CINF', 'NTAP', 'DHI',
			  	 'LEN', 'HCP', 'CBRE', 'FANG', 'KEYS', 'GPC', 'WAT', 'BBY', 'BR', 'L',
			  	 'CPRT', 'RF', 'CNP', 'FCX', 'DRI', 'INCY', 'PFG', 'SJM', 'WCG', 'XYL',
			  	 'HBAN', 'EXPE', 'IFF', 'CAG', 'KMX', 'EXR', 'DOV', 'MLM', 'TFX', 'IT',
			  	 'HES', 'ANET', 'K', 'HST', 'MAA', 'MGM', 'DGX', 'CE', 'ABC', 'LNC',
			  	 'CAH', 'DXC', 'AKAM', 'TSCO', 'UDR', 'TTWO', 'HOLX', 'EXPD', 'AAL',
			  	 'CBOE', 'XRAY', 'ATO', 'ABMD', 'FOXA', 'SYMC', 'GWW', 'KSU',', CTXS',
			  	 'SWKS', 'HAS', 'VNO', 'VAR', 'LNT', 'ETFC', 'CMA', 'BHGE', 'TXT', 'REG',
			  	 'NCLH', 'STX', 'MAS', 'AAP', 'DRE', 'DVN', 'HRL', 'CHRW', 'MRO', 'SIVB',
			  	 'COG', 'RJF', 'AES', 'NDAQ', 'PNW', 'WYNN', 'TAP', 'FTNT', 'NI', 'FMC',
			  	 'APA', 'UHS', 'JKHY', 'RE', 'HSIC', 'NRG', 'VIAB', 'NBL', 'BEN', 'PKI',
			  	 'EMN', 'TIF', 'FRT', 'ARNC', 'URI', 'CF', 'ALLE', 'CTL', 'JEC', 'GRMN',
			  	 'AVY', 'DISCK', 'HII', 'FTI', 'LW', 'JNPR', 'MHK', 'TMK', 'MYL', 'WRK',
			  	 'SNA', 'BF.B', 'WAB', 'IRM', 'WU', 'PKG', 'TPR', 'ZION', 'IVZ', 'FFIV',
			  	 'LKQ', 'PHM', 'IPG', 'KSS', 'DISH', 'BWA', 'NLSN', 'AIV', 'WHR', 'NOV', 'CPB',
			  	 'QRVO', 'MOS', 'KIM', 'SLG', 'JBHT', 'ALK', 'FBHS', 'ALB', 'UNM', 'SEE',
			  	 'PVH', 'FLIR', 'XRX', 'RHI', 'ADS', 'HFC', 'M', 'FLS', 'RL', 'AOS', 'PBCT',
			  	 'PNR', 'DVA', 'COTY', 'HBI', 'NWL', 'NKTR', 'HOG', 'XEC', 'ROL', 'HRB',
			  	 'PRGO', 'FOX', 'HP', 'PWR', 'AIZ', 'CPRI', 'LB', 'LEG', 'JEF', 'FL',
			  	 'UAA', 'AMG', 'IPGP', 'TRIP', 'NWSA', 'DISCA', 'UA']